sudo: required
services:
  - docker

before_install:
  - docker build -t temmix/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true temmix/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-west-2-224922007415"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
